### PR TITLE
ratbagd-profile: modify report rate change sanity check 

### LINKED ISSUE #692: Low poll/refresh-rates not avaliable
I know this sounds like a silly issue. I mean who wants to use a lower poll-rate? But here is the point. Wine has [a problem with high mouse poll-rates](https://bugs.winehq.org/show_bug.cgi?id=33643) in multiple titles and the only fix for now is to set the poll-rate to 125Hz. Which is not possible with libratbag at least on the mice a friend of mine and I own.

Logitech G203 Prodigy
Logitech G700
Both mice support poll-rates of 125, 250, 500 and 1000Hz on Windows, but the lower two (125 & 250) are not available in libratbag+piper.

I am not sure if its possible to enable the low poll-rates for every mouse. But it would be great to maybe support setting the supported refresh-rates in the device config?

thanks in advance,
Riesi

### LINKED ISSUE #1126: Polling rates are not set correctly
**Information**

- `ratbagd` version (`ratbagd --version`): 0.15
- Distribution: Arch Linux
- Kernel version (ex. `uname -srmo`): `Linux 5.10.11-hardened1-1-hardened x86_64 GNU/Linux`

Device info:
```
hooting-chinchilla - Logitech G Pro
Model: usb:046d:4079:0
```

**Describe the bug**
It looks like mouse polling rates are set only in steps of 100, even if given another value. 
When i try to set 125 i get 100 and 200 instead of 250. All verified with [evhz](https://git.sr.ht/~iank/evhz).
It was also mentioned [here](https://github.com/libratbag/libratbag/issues/692#issuecomment-496304983), however it's not the reporting of ratbagctl that's wrong, but the actual polling rate that's being set.

Another problem it that currently ratbagctl can set polling rates not officially supported by manufacturers, and i imagine that can lead to problems on some hardware.

**To Reproduce**
1. `ratbagctl <device> rate get-all`
2. Set polling rate below 500, eg. 250 or 125.
3. `ratbagctl <device> rate get` You should see 100 instead of 125 or 200 instead of 250.
4. Verify with evhz

### PR DESCRIPTION
**Pull request by staticssleever668**
Fixes #692 and closes #1126. Also unblocks https://github.com/libratbag/piper/pull/494.

### CODE REVIEW

**Review by stephanlachnit — APPROVED** [review]

File: ratbagd/ratbagd-profile.c [hunk 1]
```diff
@@ -509,8 +509,6 @@ ratbagd_profile_set_report_rate(sd_bus *bus,
 	/* basic sanity check */
 	if (rate > 5000)
 		rate = 5000;
-	else if (rate % 100)
-		rate = rate - (rate % 100);
```
Comment (whot) [inline ratbagd/ratbagd-profile.c:512]: tbh, I don't recommend this change. There are very few devices that need a report rate of e.g. 476Hz and where this happens its likely more a bug than anything. The issue from a quick skim is that you need 125Hz and 250Hz to work - just add those explicitly to the list here and keep the alignment. I doubt even rates like 2100 Hz are useful - my guess is 125, 250, 500, 1000 and from then on multiples of 1000.

File: ratbagd/ratbagd-profile.c [hunk 2]
```diff
@@ -507,8 +507,8 @@ ratbagd_profile_set_report_rate(sd_bus *bus,
 		return r;
 
 	/* basic sanity check */
-	if (rate > 5000)
-		rate = 5000;
+	if (rate > 8000)
+		rate = 8000;
```
Comment (whot) [inline ratbagd/ratbagd-profile.c:511]: Which devices has a poll rate of 8000Hz? Even 5000Hz is over the top, iirc USB only supports 1000Hz anyway and the one device I've seen in the past that advertises 2000Hz does so by using multiple event nodes and then randomly sending the events through whichever one is next in the internal fw ring buffer.

**Review by whot — COMMENTED** [review]
Technically correct and does the job, I don't think it's a good idea this way though. Please see my comments above.

File: ratbagd/ratbagd-profile.c (hunk 2 above)
Comment (staticssleever668) [reply ratbagd/ratbagd-profile.c:511]: I think there is only one such mouse in the market right now - Raver Viper 8K. I don't know whether it uses a technique like the one described though.

File: ratbagd/ratbagd-profile.c (hunk 1 above)
Comment (staticssleever668) [reply ratbagd/ratbagd-profile.c:512]: I've breezed through all the drivers, and most supported report rates are 125, 250, 500 and 1000 hz. There were also several (or just one, don't remember) mice with 333 and 750 hz added to the list. Logitech G600 driver also defines support for 142, 166 and 200 hz. Checking for all of them would be cumbersome. If we do such such a check after all, I think we should align to 125 because it scales to all the most popular rates, though it won't work with these more rare report rates.
Although IMHO such check should be done on driver level. If there are devices that support such random report rates, why limit them?

Comment (stephanlachnit) [reply ratbagd/ratbagd-profile.c:512]: Tbh I don't see why limiting the report rates lower than the max makes any sense for normal use. In https://github.com/libratbag/piper/issues/491 the only reason is some issues with wine. So IMHO 125Hz (apparently HID default), 250Hz (for wine), 500Hz (max for older gaming mice), 1000Hz (normal mice) and multiple of 1000 (over-the-top mice) should be enough.

Comment (staticssleever668) [reply ratbagd/ratbagd-profile.c:512]: @stephanlachnit, I didn't quite catch that. Do you mean we should only allow 125, 250, 500 and the multiples of 1000, or we should not do the check at all?

File: ratbagd/ratbagd-profile.c (hunk 2 above)
Comment (FFY00) [reply ratbagd/ratbagd-profile.c:511]: I second this particular change. You can do 8kHz in USB HS, some high-end devices are doing this. I and designing an open source/hardware mice with a friend that supports this.

**Review by FFY00 — APPROVED** [review]
I am gonna make the call and accept this, we can revert if we find this causing any issues.
