### PR TITLE
Use macro in favor of the deprecated key button type in HID++ 1.0

### LINKED ISSUE #900: G700s: Cannot set or use macros
**Information**
- `ratbagd` version (`ratbagd --version`): 0.12
- Distribution: Arch Linux
- Kernel version: `Linux 5.4.8-arch1-1 x86_64 GNU/Linux`

**Describe the bug**
Macros show up as UNKNOWN and setting them with ratbagctl does not work. `info` will show that the macro has been mapped but the button still does not perform the macro.

**To Reproduce**
1. Plug in g700s (with macros already set from Windows)
2. Use Piper to try to set some macros. See the error "something went wrong"
3. Try to set the macro with `ratbagctl warbling-mara button 5 action set macro KEY_T`
4. Button does not perform macro

**Logs**
[output of sudo ratbagd --verbose=raw](https://github.com/libratbag/libratbag/files/4031842/log.txt)

```
$ ratbagctl warbling-mara info
warbling-mara - Logitech G700s Rechargeable Gaming Mouse
             Model: usb:046d:c07c:0
 Number of Buttons: 13
    Number of Leds: 0
Number of Profiles: 5
Profile 0: (active)
  Name: Work Default
  Report Rate: 1000Hz
  Resolutions:
    0: 2100x2100dpi (active)
    1: <disabled>
    2: <disabled>
    3: <disabled>
    4: <disabled>
  Button: 0 is mapped to 'button 1'
  Button: 1 is mapped to 'button 2'
  Button: 2 is mapped to 'button 3'
  Button: 3 is mapped to 'button 4'
  Button: 4 is mapped to 'button 5'
  Button: 5 is mapped to macro '↕T'
  Button: 6 is mapped to UNKNOWN
  Button: 7 is mapped to 'button 5'
  Button: 8 is mapped to 'button 4'
  Button: 9 is mapped to macro '↕X'
  Button: 10 is mapped to UNKNOWN
  Button: 11 is mapped to 'button 4'
  Button: 12 is mapped to 'button 5'
Profile 1: (disabled)
Profile 2: (disabled)
Profile 3: (disabled)
Profile 4: (disabled)
```

### PR DESCRIPTION
**Pull request by FFY00**
Should fix #900

I also sneaked in a fix for HID++ 2.0.

### CODE REVIEW

File: src/driver-hidpp10.c [hunk 1]
```diff
@@ -199,6 +201,14 @@ hidpp10drv_map_button(struct ratbag_device *device,
 		}
 	}
 
+	if (button->action.type == RATBAG_BUTTON_ACTION_TYPE_KEY) {
+		ret = ratbag_button_macro_new_from_keycode(button, button->action.action.key.key, modifiers);
```
Comment (stephanlachnit) [inline src/driver-hidpp10.c:205]: `rc` as return variable like below

Comment (FFY00) [reply src/driver-hidpp10.c:205]: We are using `ret` in this function. Using `rc` means creating a new variable, or bringing unrelated changes (renaming `ret` to `rc`) that just make the patch harder to understand.

We should go around the code base converting standardizing the return code variable name.

**Comment by FFY00** [comment]
It does not fix #959, it fixes #900.
