### PR TITLE
sinowealth: various improvements

### LINKED ISSUE #1158: Add G-Wolves Hati HT-M mouse support
3360 sensor, 6 buttons, has 125-500-100 polling rates support in official software (BY-COMBO3). With `lsusb` it shows up as `ID 258a:0027 SINOWEALTH Wired Gaming Mouse`. It doesn't work with current Sinowealth driver because of different config command and response length.

Some code snippets:
Configuring angle snapping and lift-off distance:
```c
#define SINOWEALTH_CMD_ANGLESNAPPING_AND_LOD 0x1b

/* Set angle snapping (Cal line) and lift-off distance (LOD) modes */
const bool anglesnapping_enabled = false;
const bool lod_high = true;
uint8_t anglesnapping_lod[6] = {SINOWEALTH_REPORT_ID_CMD, SINOWEALTH_CMD_ANGLESNAPPING_AND_LOD, 1 + lod_high, anglesnapping_enabled};
rc = ratbag_hidraw_set_feature_report(device, SINOWEALTH_REPORT_ID_CMD, anglesnapping_lod, sizeof(anglesnapping_lod));
if (rc != sizeof(anglesnapping_lod)) {
	log_error(device->ratbag, "Error while sending read config command: %d\n", rc);
	return -1;
}
/* Print angle snapping (Cal line) and lift-off distance (LOD) modes */
uint8_t anglesnapping_lod_get[6] = {SINOWEALTH_REPORT_ID_CMD, SINOWEALTH_CMD_ANGLESNAPPING_AND_LOD};
rc = ratbag_hidraw_set_feature_report(device, SINOWEALTH_REPORT_ID_CMD, anglesnapping_lod_get, sizeof(anglesnapping_lod_get));
if (rc != sizeof(anglesnapping_lod_get)) {
	log_error(device->ratbag, "Error while sending read config command: %d\n", rc);
	return -1;
}
rc = ratbag_hidraw_get_feature_report(device, SINOWEALTH_REPORT_ID_CMD, anglesnapping_lod_get, sizeof(anglesnapping_lod_get));
if (rc != sizeof(anglesnapping_lod_get)) {
	log_error(device->ratbag, "Error while sending read config command: %d\n", rc);
	return -1;
}
log_info(device->ratbag, "LOD is high: %u; Angle snapping enabled: %u\n", anglesnapping_lod_get[2] - 1, anglesnapping_lod_get[3]);
```
Configuring debounce time:
```c
#define SINOWEALTH_CMD_DEBOUNCE 0x1a

/* Set debounce time
 * The value for it is ms/2
 * For example, 4 ms is 0x2, 2 ms in 0x1
*/
uint8_t debounce[6] = {SINOWEALTH_REPORT_ID_CMD, SINOWEALTH_CMD_DEBOUNCE, 0x1};
rc = ratbag_hidraw_set_feature_report(device, SINOWEALTH_REPORT_ID_CMD, debounce, sizeof(debounce));
if (rc != sizeof(debounce)) {
	log_error(device->ratbag, "Error while sending read config command: %d\n", rc);
	return -1;
}
/* Print debounce time */
uint8_t debounce_get[6] = {SINOWEALTH_REPORT_ID_CMD, SINOWEALTH_CMD_DEBOUNCE, 0x1};
rc = ratbag_hidraw_set_feature_report(device, SINOWEALTH_REPORT_ID_CMD, debounce_get, sizeof(debounce_get));
if (rc != sizeof(debounce_get)) {
	log_error(device->ratbag, "Error while sending read config command: %d\n", rc);
	return -1;
}
rc = ratbag_hidraw_get_feature_report(device, SINOWEALTH_REPORT_ID_CMD, debounce_get, sizeof(debounce_get));
if (rc != sizeof(debounce_get)) {
	log_error(device->ratbag, "Error while sending read config command: %d\n", rc);
	return -1;
}
log_info(device->ratbag, "debounce: %u ms\n", debounce_get[2] * 2);
```

### PR DESCRIPTION
**Pull request by staticssleever668**
Sorry for putting so many commits in one PR, this would've taken me 10 times longer if I did this on separate branches, though now it would probably take 10 more times to review it :).
Some stuff, for example DPI conversions formulas, is taken from #1065.

Closes #1065.

Highlights:
- Improve code style for clarity and easier maintainability.
- Support different LED types (RGB and RGB) and different sensors (PWM3327, PWM3360, PWM3389).
- Support some new mice: Genesis Xenon 770, DreamMachines DM5, G-Wolves Hati HT-M Wired Classic and Ace (Fixes #1158), Glorious Model O with old firmwares. Detection is based on firmware version (each mouse has a unique firmware version, apparently).
- Profile selection.
- Printing of currently selected profile, lift-off distance, angle snapping and debounce time.

@hrw, hi, I also added support for Genesis Xenon 770 you seemed to have had a few months ago, could you give it a try? Specifically I want LEDs to be checked, I may have swapped green and blue channels, and also I'm not completely sure DPI is 100% correct (though even if it's wrong it should be ~5% away from intended value in the worst case).

Offtopic: 
While searching for firmware versions different mice have, which required me to install configuration software for various mice models, I managed to accidentally `update` firmware of my G-Wolves mouse to one of Glorious mice. As I had nothing to lose after that I tried firmware updates for some different mice models but to no avail none of them install. And I couldn't even take a packet dump of how the update procedure looks. ;(
I tried to modify the update software, but putting device into DFU mode is as far as I could go. Help would be appreciated.
Now on software level I have a Glorious Model O with absolutely nothing left from original firmware. :^)

### CODE REVIEW

**Comment by staticssleever668** [comment]
I restructured this PR a bit. I will add button changing support separately.

File: src/driver-sinowealth.c [hunk 1]
```diff
@@ -47,171 +63,279 @@
...
+sinowealth_raw_to_color(struct ratbag_device *device, struct sinowealth_color raw)
 {
-	return (struct ratbag_color) {.red = raw.r, .green = raw.g, .blue = raw.b};
+	struct sinowealth_data *drv_data = device->drv_data;
+
+	switch (drv_data->led_type) {
+	case LED_RGB: return (struct ratbag_color){ .red = raw.data[0], .green = raw.data[1], .blue = raw.data[2] };
+	default:
+	case LED_RBG: return (struct ratbag_color){ .red = raw.data[0], .green = raw.data[2], .blue = raw.data[1] };
+	}
```
Comment (whot) [inline src/driver-sinowealth.c:300]: I think this would be a lot more readable with a temporary variable for the `ratbag_color` to return.

File: src/driver-sinowealth.c [hunk 2]
```diff
@@ -265,81 +458,144 @@ sinowealth_print_fw_version(struct ratbag_device *device) {
...
-	uint8_t cmd[6] = {SINOWEALTH_REPORT_ID_CMD, SINOWEALTH_CMD_GET_CONFIG};
+	uint8_t cmd[SINOWEALTH_CMD_SIZE] = { SINOWEALTH_REPORT_ID_CMD, SINOWEALTH_CMD_GET_CONFIG };
 	rc = ratbag_hidraw_set_feature_report(device, SINOWEALTH_REPORT_ID_CMD, cmd, sizeof(cmd));
 	if (rc != sizeof(cmd)) {
 		log_error(device->ratbag, "Error while sending read config command: %d\n", rc);
 		return -1;
 	}
 
-	const char config_report_id = drv_data->is_long ? SINOWEALTH_REPORT_ID_CONFIG_LONG : SINOWEALTH_REPORT_ID_CONFIG;
+	const unsigned char config_report_id = drv_data->is_long ? SINOWEALTH_REPORT_ID_CONFIG_LONG : SINOWEALTH_REPORT_ID_CONFIG;
```
Comment (whot) [inline src/driver-sinowealth.c:560]: do we get any benefit out of this being a char? Couldn't this just be a `uint8_t`? Or does the compiler complain here?

Arguably, we should change `ratbag_hidraw_get_feature_report()` to take the uint8_t instead of a char.

**Review by whot — APPROVED** [review]
A few general comments, I skimmed through the rest and this looks good to me. You are the authority on whether it works so we can merge this when you're ready :)

File: src/driver-sinowealth.c [hunk 3]
```diff
@@ -47,171 +63,279 @@
...
+ * This naming may be incorrect as it's not actually known waht the other bits do.
+ */
+enum sinowealth_config_data_mask {
+	SINOWEALTH_XY_INDEPENDENT = 0b1000,
+};
 
-struct sinowealth_rbg8 {
-	uint8_t r, b, g;
+struct sinowealth_color {
+	uint8_t data[3];
```
[the remark this answers is not in the document]
Comment (staticssleever668) [reply src/driver-sinowealth.c:80]: Fixed, thank you.

File: src/driver-sinowealth.c [hunk 4]
```diff
@@ -47,171 +63,279 @@
...
 	uint8_t unknown2[6];
-	/*
-	 * 0x1/2/3/4 - report rate (125, 250, 500, 1000 hz).
-	 * 0x80 - SINOWEALTH_XY_INDEPENDENT.
-	 */
-	uint8_t config;
+	/* @ref sinowealth_report_rate_map. */
+	uint8_t report_rate:4;
+	/* 0b1000 - make DPI axes independent. */
+	uint8_t config:4;
```
[the remark this answers is not in the document]
Comment (staticssleever668) [reply src/driver-sinowealth.c:147]: Fixed, thank you.

File: src/driver-sinowealth.c (hunk 2 above)
Comment (staticssleever668) [reply src/driver-sinowealth.c:560]: I originally made this change because of the following clang-tidy warning about it's usage in `sinowealth_write_config`: `'signed char' to 'enum sinowealth_report_id' conversion; consider casting to 'unsigned char' first.`. 
Though you are right, I should've used `uint8_t` instead of `unsigned char`.
Fixed, thank you.

File: src/driver-sinowealth.c (hunk 1 above)
Comment (staticssleever668) [reply src/driver-sinowealth.c:300]: Fixed. Thank you!

**Comment by staticssleever668** [comment]
Had RBG and RGB in reverse, fixed and squashed fixes for the suggestions while I had a chance.

File: src/driver-sinowealth.c [hunk 5]
```diff
@@ -33,7 +33,7 @@
 #define SINOWEALTH_CONFIG_SIZE_USED_MIN 131
 #define SINOWEALTH_CONFIG_SIZE_USED_MAX 167
 
-#define SINOWEALTH_XY_INDEPENDENT 0x80
+#define SINOWEALTH_XY_INDEPENDENT 0b1000
```
Comment (whot) [inline src/driver-sinowealth.c]: commenting on the commit message here (which github doesn't let you): it's "nibbles", not "nimbles".

Comment (staticssleever668) [reply src/driver-sinowealth.c]: Oh, so that's why spell checker was bugging me... Thank you, fixed!

**Comment by whot** [comment]
merged, thanks!

**Comment by hrw** [comment]
@staticssleever668 I gave it a try.

My x770 is detected:

```
13:48 (s) marcin@puchatek:build$ ratbagctl
singing-gundi:       SINOWEALTH Wired Gaming Mouse
13:49 (s) marcin@puchatek:build$ ratbagctl singing-gundi info
singing-gundi - SINOWEALTH Wired Gaming Mouse
             Model: usb:258a:0027:0
 Number of Buttons: 0
    Number of Leds: 1
Number of Profiles: 1
Profile 0: (active)
  Name: n/a
  Report Rate: 1000Hz
  Resolutions:
    0: 700x700dpi
    1: 1100x1100dpi
    2: 3400x3400dpi
    3: 3600x3600dpi (active) (default)
    4: 4700x4700dpi
    5: 6100x6100dpi
    6: <disabled>
    7: <disabled>
  LED: 0, depth: rgb, mode: breathing, color: 33d17a, duration: 0, brightness: 214
```

Will try to find some time and make it working properly. Mouse has 2 leds (bottom strip detected as LED 0 and scrollwheel+logo which change on DPI change) and can have 9 or 16 buttons depends on which set of buttons is mounted under thumb (Back/Forward only or 9 buttons one).

I have Windows 10 VM with original software installed so can compare values.

**Comment by hrw** [comment]
More X770 checks:

- RGB colours are set in proper way (ff0000 is red, 00ff00 is green, 0000ff is blue)
- led on/off/cycle work (I am unable to get breathing effect working with ratbagctl nor piper)

**Comment by whot** [comment]
fwiw, `ratbagctl singing-gundi info` - the custom device names aren't necessary anymore, we've had substring matching for ages and `ratbagctl SINOWEALTH info` would work in your case.
